### ISSUE TITLE
盒子在div中出现无法清除浮动的问题

### ISSUE THREAD

**Issue by Stonmore** [JohnRisewhy/FirstDemo#1]
Test

**Comment by Swallowyy** [comment]
test

**Comment by Swallowyy** [comment]
dGhlcmUncyBzb21ldGhpbmcgYWJvdXQgeXkgb24geW91ciBnaXQncyBob21lIHBhZ2U=

> 测试

**Comment by ChouDay** [comment]
SSBzYXcgaXQsIGl0IGlzIG9rICwgSSBjYW4gbm90IGxvZ2luIGdpdHViIHdpdGhvdXQgdnBuICxob3cgYXJlIHU

**Comment by Swallowyy** [comment]
> 测试

SSdtIG9rYXku

**Comment by Stonmore** [comment]
我用#CSDN#这个app发现了有技术含量的博客，小伙伴们求同去《如何使用IDEA进行协作编码，共享项目，并实时的处理》, 一起来围观吧 https://blog.csdn.net/qq_44774831/article/details/116136469?utm_source=app&app_version=5.0.0

**Comment by JohnRisewhy** [comment]
> 我用同一个应用程序发现了有合作伙伴的技术含量##CSDN，大家求一起去如何使用协作吧#CSDN 协作协作，共享项目，并进行协作的项目，并一起[围观。 net/qq_44774831/article/details/116136469?utm_source=app&app_version=5.0.0](https://blog.csdn.net/qq_44774831/article/details/116136469?utm_source=app&app_version=5.0.0)

https://code-with-me.jetbrains.com/agbAkPiGBentChIh6KDT4w#p=IU&fp=56AE3FCF9F1CAFA95A079CAB030A4FAB5BC2092E0C8589CA75B246FBC93DEA26

**Comment by Stonmore** [comment]
https://code-with-me.jetbrains.com/wiJh5_TcopGUXIiB-qehFw#p=IU&fp=BF490DD01B3B23F927D9E3C65A39443C4D332DB4B84EBEA47E1E5486320F09B3

**Comment by Stonmore** [comment]
Z29pbmcgb3V0LHdhaXQgdSBuaWdodA==

**Comment by Stonmore** [comment]
https://code-with-me.jetbrains.com/Np_eC_bXx1ap1PuzQxIfOQ#p=IU&fp=98103722121BC1CC3B487247162CE1362DA0085078457B2CE5A1FA1299C9F8DE

**Comment by Stonmore** [comment]
https://code-with-me.jetbrains.com/O-8l2p9BCU3OKOclFxDWBg#p=IU&fp=98103722121BC1CC3B487247162CE1362DA0085078457B2CE5A1FA1299C9F8DE

**Comment by JohnRisewhy** [comment]
connect没响应

**Comment by Stonmore** [comment]
https://code-with-me.jetbrains.com/frNNwqVkZbhOBFL1hOqFiw#p=IU&fp=98103722121BC1CC3B487247162CE1362DA0085078457B2CE5A1FA1299C9F8DE

**Comment by Stonmore** [comment]
552h6KeJ5ZCn77yM6YKu566x5riF55CG5LiA5LiL77yM5oOz5L2g

**Comment by Stonmore** [comment]
6YKu566x5Yig6Zmk5ZCO6L+Y5pyJ5Zue5pS256uZ77yM5Zue5pS256uZ5Lmf6KaB5Yig6Zmk

**Comment by JohnRisewhy** [comment]
55+l6YGT5ZWmIMK35pS+5b+DwrfCt8K3bWlzcyB1IDI=
